# Generated by Django 5.1.4 on 2025-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="add",
            field=models.FloatField(default=0.0),
        ),
    ]
