# Generated by Django 5.1.4 on 2025-04-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
