# Generated by Django 5.1.4 on 2025-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_users_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="users",
            name="user",
            field=models.CharField(max_length=30),
        ),
    ]
