# Generated by Django 5.1.4 on 2025-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                default="test@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="user",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
